<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\AreaBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * STATIONS — the places in an area that people work out of.
 *
 * A NEW TABLE, so every required column is required from the start: there are
 * no existing rows to require it of, and nothing to expand, backfill and
 * contract. The columns that are nullable are the facts genuinely sometimes
 * unknown — the radio code an installation may not use, the elevation and the
 * locality nobody may have recorded, the day it opened — plus the derived
 * zone, where null is the legal answer rather than a missing one.
 *
 * CASCADE ON THE AREA, SET NULL ON THE ZONE, and the asymmetry is the model.
 * A station lives and dies with its area, as a zone does. Removing a ZONE must
 * never delete the posts standing in it: they become unzoned, which is a state
 * the product already draws, so the derived pointer is cleared and the row
 * stays.
 *
 * THE GiST INDEX is what makes the derivation affordable. Every zone write
 * re-asks which zone each of the area's stations is in, in one statement, and
 * that statement is a point-in-polygon per row.
 *
 * NO DATA ARRIVES WITH THIS MIGRATION. `patrol-module` has a `station` of its
 * own and keeps it; moving those rows to this table is a coordinated round of
 * its own, named in the area bundle's design decisions, and nothing here reads
 * or writes that table.
 */
final class Version20260101000140 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'station: the places in an area that people work out of, with the zone derived from the point';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE station (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              area_id INT NOT NULL,
              zone_id INT DEFAULT NULL,
              name VARCHAR(128) NOT NULL,
              code VARCHAR(32) DEFAULT NULL,
              point geometry(POINT, 4326) NOT NULL,
              elevation_m INT DEFAULT NULL,
              locality VARCHAR(96) DEFAULT NULL,
              active BOOLEAN NOT NULL,
              opened_at DATE DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              uuid UUID NOT NULL,
              PRIMARY KEY(id)
            )
            SQL);
        // The mapping-derived names, as the sibling tables carry them: a
        // hand-picked name here is a name `migrations:diff` renames back.
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F39F8B1D17F50A6 ON station (uuid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_station_area_name ON station (area_id, name)');
        $this->addSql('CREATE INDEX IDX_9F39F8B1BD0F409C ON station (area_id)');
        $this->addSql('CREATE INDEX IDX_9F39F8B19F2C3FAB ON station (zone_id)');
        // The derivation is a point-in-polygon per station on every zone write.
        $this->addSql('CREATE INDEX idx_station_point_sp ON station USING gist (point)');
        $this->addSql('ALTER TABLE station ADD CONSTRAINT FK_STATION_AREA FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE station ADD CONSTRAINT FK_STATION_ZONE FOREIGN KEY (zone_id) REFERENCES zone (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    /** @destructive drops every station and the postings that will hang off them. */
    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE station DROP CONSTRAINT FK_STATION_ZONE');
        $this->addSql('ALTER TABLE station DROP CONSTRAINT FK_STATION_AREA');
        $this->addSql('DROP TABLE station');
    }
}
