<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\AreaBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * POSTINGS — who works out of which station.
 *
 * DATED AFTER THE AREA'S OTHERS, AND AFTER TEAM'S, for the reason the shell's
 * own `widget_preference` is dated last: this table references `team_user` —
 * the association is mapped to the published user contract and resolved to
 * the team bundle's entity — and a referencing table's migration is dated
 * after the migration that creates what it references. The core ships as one
 * package with one history ordered by these timestamps, so a `posting` dated
 * among the area's own would run before `team_user` existed and fail on the
 * constraint.
 *
 * THE MAPPING STILL POINTS AT THE CONTRACT, not at that class, which is what
 * lets the area bundle compile and run without the team bundle at all. An
 * installation that resolves the contract to its own account class replaces
 * this constraint too — the same bargain overriding `resolve_target_entities`
 * already is, and documented where that escape hatch is.
 *
 * NO UNIQUE INDEX ON THE LEADER, and this one is worth reading twice. One
 * leader per station is a rule about STANDING postings, so the constraint
 * that expresses it is PARTIAL — `UNIQUE (station_id) WHERE leader AND
 * ended_at IS NULL`. The ORM mapping cannot declare a partial index, so one
 * written here by hand is one `doctrine:migrations:diff` drops on its next
 * run, and a constraint that disappears silently is worse than a rule that
 * was never claimed. The rule lives in the service, in a transaction, with
 * tests; tightening it is named in the bundle's design decisions.
 *
 * A NEW TABLE, so every required column is required from the start.
 */
final class Version20260101000500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'posting: who works out of which station, and who leads there';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE posting (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              station_id INT NOT NULL,
              person_id INT NOT NULL,
              since DATE NOT NULL,
              ended_at DATE DEFAULT NULL,
              leader BOOLEAN NOT NULL,
              source VARCHAR(16) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              uuid UUID NOT NULL,
              PRIMARY KEY(id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BD275D73D17F50A6 ON posting (uuid)');
        $this->addSql('CREATE INDEX IDX_BD275D7321BDB235 ON posting (station_id)');
        $this->addSql('CREATE INDEX IDX_BD275D73217BBB47 ON posting (person_id)');
        $this->addSql('ALTER TABLE posting ADD CONSTRAINT FK_POSTING_STATION FOREIGN KEY (station_id) REFERENCES station (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE posting ADD CONSTRAINT FK_BD275D73217BBB47 FOREIGN KEY (person_id) REFERENCES team_user (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    /** @destructive drops every posting; who worked where is not recorded anywhere else. */
    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE posting DROP CONSTRAINT FK_BD275D73217BBB47');
        $this->addSql('ALTER TABLE posting DROP CONSTRAINT FK_POSTING_STATION');
        $this->addSql('DROP TABLE posting');
    }
}
