<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\AreaBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * THE DAY, AND THE PINGS THAT PROVE IT — API-CONTRACT.md §13.
 *
 * FOUR TABLES AND ONE COLUMN. The claim a ranger makes in the morning,
 * the words their area lets them make it in, the second claims that may
 * overtake it, and the positions their phone reported while the watch
 * was open — plus what "inside this post" means, on the post.
 *
 * NOTHING HERE STORES A JUDGEMENT. There is no `verified` column and
 * there will not be one: whether a position bears a claim out is
 * computed on read from the post's catchment, so a catchment corrected
 * next month re-derives every day that used it. A stored verdict would
 * be a verdict nobody could correct.
 *
 * THE INSTANTS CARRY THEIR OFFSET (`TIMESTAMP WITH TIME ZONE`) and the
 * ranger's own date is a separate `DATE`. A 06:00 watch belongs to that
 * date whatever the offset says, and the two are not derivable from
 * each other.
 *
 * A STATUS IS RESTRICTED, NEVER CASCADED: an area deactivates a status
 * rather than deleting it, precisely so that a day already recorded
 * keeps the answer it was given.
 *
 * EXPAND ONLY. Nothing existing is altered but the station's new
 * nullable catchment, and null there is a real state — a post with no
 * ring has no inside, and the handset says so rather than inventing a
 * radius.
 */
final class Version20260921000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'duty_checkin, duty_checkin_status, duty_checkin_correction, duty_position, station.catchment_m';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE duty_checkin (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_ref VARCHAR(64) NOT NULL, local_date DATE NOT NULL, occurred_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, position geometry(POINT,4326) DEFAULT NULL, position_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, accuracy_m DOUBLE PRECISION DEFAULT NULL, device_id VARCHAR(64) NOT NULL, app_version VARCHAR(32) NOT NULL, note TEXT DEFAULT NULL, ended_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, handover_note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, area_id INT NOT NULL, status_id INT NOT NULL, station_id INT DEFAULT NULL, person_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_duty_checkin_day ON duty_checkin (area_id, local_date)');
        $this->addSql('CREATE UNIQUE INDEX uniq_duty_checkin_ref ON duty_checkin (area_id, client_ref)');
        $this->addSql('CREATE INDEX IDX_8C5F1D40BD0F409C ON duty_checkin (area_id)');
        $this->addSql('CREATE INDEX IDX_8C5F1D406BF700BD ON duty_checkin (status_id)');
        $this->addSql('CREATE INDEX IDX_8C5F1D4021BDB235 ON duty_checkin (station_id)');
        $this->addSql('CREATE INDEX IDX_8C5F1D40217BBB47 ON duty_checkin (person_id)');
        $this->addSql('CREATE INDEX idx_duty_checkin_position_sp ON duty_checkin USING gist (position)');
        $this->addSql('CREATE TABLE duty_checkin_correction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_ref VARCHAR(64) NOT NULL, effective_from TIMESTAMP(0) WITH TIME ZONE NOT NULL, note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, checkin_id INT NOT NULL, status_id INT NOT NULL, station_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_duty_correction_ref ON duty_checkin_correction (checkin_id, client_ref)');
        $this->addSql('CREATE INDEX IDX_6CB15C45A85C7AA9 ON duty_checkin_correction (checkin_id)');
        $this->addSql('CREATE INDEX IDX_6CB15C456BF700BD ON duty_checkin_correction (status_id)');
        $this->addSql('CREATE INDEX IDX_6CB15C4521BDB235 ON duty_checkin_correction (station_id)');
        $this->addSql('CREATE TABLE duty_checkin_status (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status_key VARCHAR(32) NOT NULL, label VARCHAR(64) NOT NULL, kind VARCHAR(24) NOT NULL, position INT NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uuid UUID NOT NULL, area_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64BCB73AD17F50A6 ON duty_checkin_status (uuid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_duty_status_key ON duty_checkin_status (area_id, status_key)');
        $this->addSql('CREATE INDEX IDX_64BCB73ABD0F409C ON duty_checkin_status (area_id)');
        $this->addSql('CREATE TABLE duty_position (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_ref VARCHAR(64) NOT NULL, recorded_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, position geometry(POINT,4326) NOT NULL, accuracy_m DOUBLE PRECISION NOT NULL, battery_pct INT DEFAULT NULL, source VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, area_id INT NOT NULL, checkin_id INT NOT NULL, person_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_duty_position_watch ON duty_position (checkin_id, recorded_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_duty_position_ref ON duty_position (area_id, client_ref)');
        $this->addSql('CREATE INDEX IDX_B7953AB6BD0F409C ON duty_position (area_id)');
        $this->addSql('CREATE INDEX IDX_B7953AB6A85C7AA9 ON duty_position (checkin_id)');
        $this->addSql('CREATE INDEX IDX_B7953AB6217BBB47 ON duty_position (person_id)');
        $this->addSql('CREATE INDEX idx_duty_position_position_sp ON duty_position USING gist (position)');
        $this->addSql('ALTER TABLE duty_checkin ADD CONSTRAINT FK_8C5F1D40BD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_checkin ADD CONSTRAINT FK_8C5F1D406BF700BD FOREIGN KEY (status_id) REFERENCES duty_checkin_status (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_checkin ADD CONSTRAINT FK_8C5F1D4021BDB235 FOREIGN KEY (station_id) REFERENCES station (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_checkin ADD CONSTRAINT FK_8C5F1D40217BBB47 FOREIGN KEY (person_id) REFERENCES team_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_checkin_correction ADD CONSTRAINT FK_6CB15C45A85C7AA9 FOREIGN KEY (checkin_id) REFERENCES duty_checkin (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_checkin_correction ADD CONSTRAINT FK_6CB15C456BF700BD FOREIGN KEY (status_id) REFERENCES duty_checkin_status (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_checkin_correction ADD CONSTRAINT FK_6CB15C4521BDB235 FOREIGN KEY (station_id) REFERENCES station (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_checkin_status ADD CONSTRAINT FK_64BCB73ABD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_position ADD CONSTRAINT FK_B7953AB6BD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_position ADD CONSTRAINT FK_B7953AB6A85C7AA9 FOREIGN KEY (checkin_id) REFERENCES duty_checkin (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_position ADD CONSTRAINT FK_B7953AB6217BBB47 FOREIGN KEY (person_id) REFERENCES team_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE station ADD catchment_m INT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE station DROP catchment_m');
        $this->addSql('DROP TABLE duty_position');
        $this->addSql('DROP TABLE duty_checkin_correction');
        $this->addSql('DROP TABLE duty_checkin');
        $this->addSql('DROP TABLE duty_checkin_status');
    }
}
