<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\AreaBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * WHAT HAPPENED TO AN AREA'S ZONE SET — one row per event, and no geometry.
 *
 * NOTHING IS BACKFILLED. An installation that already has zones has no record
 * of how they got there, and inventing lines for imports nobody logged would
 * be a worse answer than an empty log. The table starts empty and fills from
 * the day it exists, which is what a log is.
 *
 * A NEW TABLE, SO EVERY REQUIRED COLUMN IS REQUIRED FROM THE START: there are
 * no existing rows to require it of, so there is nothing to expand, backfill
 * and tighten. The only nullable columns are the two facts that are genuinely
 * sometimes unknown — who did it, where nobody was signed in, and the
 * qualification after a headline that says it all.
 *
 * CASCADE ON THE AREA, as the zones and the imports already do: deleting an
 * area takes what was only ever about that area.
 */
final class Version20260101000120 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'zone_event: the log of what happened to an area’s zone set';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE zone_event (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              area_id INT NOT NULL,
              kind VARCHAR(32) NOT NULL,
              headline VARCHAR(512) NOT NULL,
              detail VARCHAR(512) DEFAULT NULL,
              actor VARCHAR(180) DEFAULT NULL,
              occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY(id)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_zone_event_area_time ON zone_event (area_id, occurred_at)');
        $this->addSql('ALTER TABLE zone_event ADD CONSTRAINT FK_ZONE_EVENT_AREA FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    /** @destructive drops the whole log; there is no other copy of it. */
    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE zone_event DROP CONSTRAINT FK_ZONE_EVENT_AREA');
        $this->addSql('DROP TABLE zone_event');
    }
}
