<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\AreaBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * THE GROUND: the named piece of it an installation manages, and the zones
 * inside that.
 *
 * Dated before every other bundle's tables because both of the core's
 * cross-bundle foreign keys point here — the registry's per-area ledger and the
 * team's area-scoped departments — and a referenced table has to exist first.
 *
 * The GiST index on each geometry column comes from the mapping, not from a
 * hand-written line: `fundistadi/postgis-bundle` declares it, and it is here
 * because a diff put it here.
 */
final class Version20260101000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'area_of_interest and zone';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE area_of_interest (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(128) NOT NULL,
              geom geometry(MULTIPOLYGON, 4326) DEFAULT NULL,
              source VARCHAR(64) DEFAULT NULL,
              iucn_category VARCHAR(8) DEFAULT NULL,
              established_year INT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              uuid UUID NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FB9E46FCD17F50A6 ON area_of_interest (uuid)');
        $this->addSql('CREATE INDEX idx_area_of_interest_geom_sp ON area_of_interest USING gist (geom)');

        $this->addSql(<<<'SQL'
            CREATE TABLE zone (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(128) NOT NULL,
              geom geometry(MULTIPOLYGON, 4326) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              uuid UUID NOT NULL,
              area_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A0EBC007D17F50A6 ON zone (uuid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_zone_area_name ON zone (area_id, name)');
        $this->addSql('CREATE INDEX IDX_A0EBC007BD0F409C ON zone (area_id)');
        $this->addSql('CREATE INDEX idx_zone_geom_sp ON zone USING gist (geom)');

        $this->addSql('ALTER TABLE zone ADD CONSTRAINT FK_A0EBC007BD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE zone DROP CONSTRAINT FK_A0EBC007BD0F409C');
        $this->addSql('DROP TABLE zone');
        $this->addSql('DROP TABLE area_of_interest');
    }
}
