<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\AreaBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * WHAT HAPPENED AT A POST — one row per event, and no superseded state.
 *
 * NOTHING IS BACKFILLED. A station recorded before this table existed has no
 * log, and inventing lines for events nobody logged would be a worse answer
 * than an empty card. The log fills from the day it exists, which is what a
 * log is.
 *
 * CASCADE ON THE STATION, which cascades on the area. A post that closes is
 * DEACTIVATED and keeps every line; only deleting the area takes them, and it
 * takes the station too.
 *
 * NO FOREIGN KEY ANYWHERE ELSE, on purpose: a line names a person in its own
 * sentence and never points at them, because "M. Kisanga's posting ended" has
 * to still say so after the account is gone.
 */
final class Version20260101000160 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'station_event: the log of what happened at a post';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE station_event (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              station_id INT NOT NULL,
              kind VARCHAR(32) NOT NULL,
              headline VARCHAR(512) NOT NULL,
              detail VARCHAR(512) DEFAULT NULL,
              actor VARCHAR(180) DEFAULT NULL,
              occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY(id)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_station_event_station_time ON station_event (station_id, occurred_at)');
        $this->addSql('ALTER TABLE station_event ADD CONSTRAINT FK_STATION_EVENT_STATION FOREIGN KEY (station_id) REFERENCES station (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    /** @destructive drops every station's log; there is no other copy of it. */
    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE station_event DROP CONSTRAINT FK_STATION_EVENT_STATION');
        $this->addSql('DROP TABLE station_event');
    }
}
