<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\AreaBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * WHERE A ZONING SCHEME CAME FROM — one row per import, and a nullable pointer
 * to it from every zone.
 *
 * NOTHING IS BACKFILLED AND NOTHING BECOMES REQUIRED. An installation that
 * already has zones has no provenance to give them: nobody recorded which file
 * a zone drawn last year came out of, and inventing one would be a worse answer
 * than none. So `zone.import_id` ships nullable and stays nullable — a null
 * says "not recorded", which is true — and every column that IS required lives
 * on the new table, where there are no existing rows to require it of.
 *
 * SET NULL ON THE ZONE, CASCADE ON THE AREA. Losing the record of where a
 * scheme came from must not delete the scheme; deleting the area takes both, as
 * it already takes the zones.
 */
final class Version20260101000110 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'zone_import: the provenance of an imported zoning scheme';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE zone_import (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              file_name VARCHAR(255) NOT NULL,
              imported_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              imported_by VARCHAR(180) DEFAULT NULL,
              zone_count INT NOT NULL,
              name_property VARCHAR(64) NOT NULL,
              area_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_A25DE66FBD0F409C ON zone_import (area_id)');
        $this->addSql('ALTER TABLE zone_import ADD CONSTRAINT FK_A25DE66FBD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');

        // NULLABLE, AND IT STAYS THAT WAY — see the class docblock. No UPDATE
        // belongs here: there is no value an existing zone's provenance could
        // honestly be set to.
        $this->addSql('ALTER TABLE zone ADD import_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_A0EBC007B6A263D9 ON zone (import_id)');
        $this->addSql('ALTER TABLE zone ADD CONSTRAINT FK_A0EBC007B6A263D9 FOREIGN KEY (import_id) REFERENCES zone_import (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE zone DROP CONSTRAINT FK_A0EBC007B6A263D9');
        $this->addSql('DROP INDEX IDX_A0EBC007B6A263D9');
        $this->addSql('ALTER TABLE zone DROP import_id');
        $this->addSql('ALTER TABLE zone_import DROP CONSTRAINT FK_A25DE66FBD0F409C');
        $this->addSql('DROP TABLE zone_import');
    }
}
