<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\TeamBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * THE INSTALLATION'S OWN PERIOD FIGURES — the same history one scope up.
 *
 * EXPAND ONLY, AND NOTHING IS BACKFILLED. A closed period cannot be
 * recomputed, which is the whole reason the table exists: the figures for
 * every month before this release were never written down and inventing them
 * from today's tables would be inventing a past. The first row arrives the
 * next time `team:performance:snapshot` runs, and until then the Team
 * overview draws no movement — which is the honest state.
 *
 * WHY IT IS NOT A NULLABLE DEPARTMENT ON THE EXISTING TABLE. Three of these
 * figures have no department to belong to, and a nullable foreign key would
 * make "a department's figure" a question with two answers — plus a unique
 * constraint that stops constraining, since Postgres allows any number of
 * rows whose NULL differs from itself.
 */
final class Version20260921000500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'team_period_figure';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE team_period_figure (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                period_key VARCHAR(16) NOT NULL,
                figure_key VARCHAR(80) NOT NULL,
                value DOUBLE PRECISION DEFAULT NULL,
                written_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_installation_period_figure ON team_period_figure (period_key, figure_key)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE team_period_figure');
    }
}
