<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\TeamBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * WHAT A DEPARTMENT SAID IT WOULD DO.
 *
 * EXPAND ONLY: a new table, nothing altered and nothing backfilled. An
 * installation that has declared no goal has none, and every surface that
 * draws the rail already says so — "no goal declared" is one of its five
 * states rather than an empty it has to explain.
 *
 * THE OWNING POSITION IS NULLED, NEVER CASCADED: a post may be retired
 * while the goal it answered for is still being reported on, and the goal
 * then reads as owned by nobody rather than disappearing with the post.
 */
final class Version20260920000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'team_department_goal';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE team_department_goal (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              department_id INT NOT NULL,
              owner_position_id INT DEFAULT NULL,
              statement VARCHAR(200) NOT NULL,
              kpi_ref VARCHAR(80) DEFAULT NULL,
              target DOUBLE PRECISION NOT NULL,
              unit VARCHAR(16) NOT NULL,
              direction VARCHAR(255) NOT NULL,
              opens_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              closes_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              uuid UUID NOT NULL,
              PRIMARY KEY(id)
            )
            SQL);
        // THE INDEX NAMES ARE DOCTRINE'S OWN, because the mapping does not
        // name them: a hand-picked name here and an auto one in the
        // metadata is a diff the schema tool writes on every run.
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7D989605D17F50A6 ON team_department_goal (uuid)');
        $this->addSql('CREATE INDEX IDX_7D989605AE80F5DF ON team_department_goal (department_id)');
        $this->addSql('CREATE INDEX IDX_7D989605DB60F1C0 ON team_department_goal (owner_position_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE team_department_goal
              ADD CONSTRAINT FK_7D989605AE80F5DF FOREIGN KEY (department_id)
              REFERENCES team_department (id) ON DELETE CASCADE
            SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE team_department_goal
              ADD CONSTRAINT FK_7D989605DB60F1C0 FOREIGN KEY (owner_position_id)
              REFERENCES team_position (id) ON DELETE SET NULL
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE team_department_goal');
    }
}
