<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\TeamBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * THE PEOPLE: the account somebody signs in with, the position that carries
 * their permissions, the department that groups positions, the record of a
 * department changing scope, and the token a field client holds.
 *
 * Two dates decide where this sits. `team_department.area_id` and
 * `team_department_scope_change.area_id` reference `area_of_interest`, so this
 * is dated after the area bundle's tables. And `widget_preference.user_id` and
 * `widget_custom_preset.user_id` reference `team_user`, so this is dated before
 * the shell's.
 */
final class Version20260101000300 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'team_department, team_position, team_user, team_department_scope_change, team_api_token';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE team_department (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(120) NOT NULL,
              active BOOLEAN DEFAULT true NOT NULL,
              deactivated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              uuid UUID NOT NULL,
              area_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F3C4934FD17F50A6 ON team_department (uuid)');
        // Two partial indexes, not one: Postgres treats NULLs as distinct, so a
        // plain unique over (name, area_id) would let an organisation-wide
        // department name repeat.
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_team_department_name_org ON team_department (name)
            WHERE
              (area_id IS NULL)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_team_department_name_area ON team_department (name, area_id)
            WHERE
              (area_id IS NOT NULL)
        SQL);
        $this->addSql('CREATE INDEX IDX_F3C4934FBD0F409C ON team_department (area_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE team_position (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(120) NOT NULL,
              permissions JSON NOT NULL,
              locked BOOLEAN NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              uuid UUID NOT NULL,
              department_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE6E388BD17F50A6 ON team_position (uuid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_team_position_department_name ON team_position (department_id, name)');
        $this->addSql('CREATE INDEX IDX_FE6E388BAE80F5DF ON team_position (department_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE team_user (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              email VARCHAR(180) NOT NULL,
              first_name VARCHAR(100) NOT NULL,
              last_name VARCHAR(100) NOT NULL,
              ranger_code VARCHAR(32) DEFAULT NULL,
              roles JSON NOT NULL,
              team_role VARCHAR(255) NOT NULL,
              is_active BOOLEAN NOT NULL,
              disabled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              invited_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              password VARCHAR(255) NOT NULL,
              is_verified BOOLEAN NOT NULL,
              verification_token VARCHAR(100) DEFAULT NULL,
              password_reset_token VARCHAR(100) DEFAULT NULL,
              password_reset_requested_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              uuid UUID NOT NULL,
              position_id INT DEFAULT NULL,
              invited_by_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C722232E7927C74 ON team_user (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C722232CE15BE12 ON team_user (ranger_code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C722232D17F50A6 ON team_user (uuid)');
        $this->addSql('CREATE INDEX IDX_5C722232DD842E46 ON team_user (position_id)');
        $this->addSql('CREATE INDEX IDX_5C722232A7B4A7E3 ON team_user (invited_by_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE team_department_scope_change (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              from_scope VARCHAR(255) NOT NULL,
              to_scope VARCHAR(255) NOT NULL,
              reason VARCHAR(1000) NOT NULL,
              recorded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              uuid UUID NOT NULL,
              department_id INT NOT NULL,
              changed_by_id INT DEFAULT NULL,
              area_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BC978FCBD17F50A6 ON team_department_scope_change (uuid)');
        $this->addSql('CREATE INDEX IDX_BC978FCBAE80F5DF ON team_department_scope_change (department_id)');
        $this->addSql('CREATE INDEX IDX_BC978FCB828AD0A0 ON team_department_scope_change (changed_by_id)');
        $this->addSql('CREATE INDEX IDX_BC978FCBBD0F409C ON team_department_scope_change (area_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE team_api_token (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              token_hash VARCHAR(64) NOT NULL,
              device_id VARCHAR(64) DEFAULT NULL,
              device_name VARCHAR(120) DEFAULT NULL,
              expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              uuid UUID NOT NULL,
              owner_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CCA7EB0CB3BC57DA ON team_api_token (token_hash)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CCA7EB0CD17F50A6 ON team_api_token (uuid)');
        $this->addSql('CREATE INDEX IDX_CCA7EB0C7E3C61F9 ON team_api_token (owner_id)');

        $this->addSql('ALTER TABLE team_department ADD CONSTRAINT FK_F3C4934FBD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_position ADD CONSTRAINT FK_FE6E388BAE80F5DF FOREIGN KEY (department_id) REFERENCES team_department (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_user ADD CONSTRAINT FK_5C722232DD842E46 FOREIGN KEY (position_id) REFERENCES team_position (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_user ADD CONSTRAINT FK_5C722232A7B4A7E3 FOREIGN KEY (invited_by_id) REFERENCES team_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_department_scope_change ADD CONSTRAINT FK_BC978FCBAE80F5DF FOREIGN KEY (department_id) REFERENCES team_department (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_department_scope_change ADD CONSTRAINT FK_BC978FCB828AD0A0 FOREIGN KEY (changed_by_id) REFERENCES team_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_department_scope_change ADD CONSTRAINT FK_BC978FCBBD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_api_token ADD CONSTRAINT FK_CCA7EB0C7E3C61F9 FOREIGN KEY (owner_id) REFERENCES team_user (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE team_api_token DROP CONSTRAINT FK_CCA7EB0C7E3C61F9');
        $this->addSql('ALTER TABLE team_department_scope_change DROP CONSTRAINT FK_BC978FCBAE80F5DF');
        $this->addSql('ALTER TABLE team_department_scope_change DROP CONSTRAINT FK_BC978FCB828AD0A0');
        $this->addSql('ALTER TABLE team_department_scope_change DROP CONSTRAINT FK_BC978FCBBD0F409C');
        $this->addSql('ALTER TABLE team_user DROP CONSTRAINT FK_5C722232DD842E46');
        $this->addSql('ALTER TABLE team_user DROP CONSTRAINT FK_5C722232A7B4A7E3');
        $this->addSql('ALTER TABLE team_position DROP CONSTRAINT FK_FE6E388BAE80F5DF');
        $this->addSql('ALTER TABLE team_department DROP CONSTRAINT FK_F3C4934FBD0F409C');
        $this->addSql('DROP TABLE team_api_token');
        $this->addSql('DROP TABLE team_department_scope_change');
        $this->addSql('DROP TABLE team_user');
        $this->addSql('DROP TABLE team_position');
        $this->addSql('DROP TABLE team_department');
    }
}
