<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\TeamBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * THE POSITION TITLES GO (ruled 2026-09-22). A title was a bare word offered
 * to every department, from the time a position was named inside its
 * department and "Analyst" twice needed one spelling. Position names are
 * unique across the organization now, nothing read the list, and the
 * vocabulary screen that edited it is retired with it.
 *
 * @destructive drops team_position_title — a list no row referenced.
 */
final class Version20260922000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'The position titles go: nothing referenced the list once position names became unique across the organization.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP TABLE team_position_title');
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE team_position_title (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                uuid UUID NOT NULL,
                name VARCHAR(120) NOT NULL,
                leads_station BOOLEAN DEFAULT false NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_208B5D41D17F50A6 ON team_position_title (uuid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_team_position_title_name ON team_position_title (name)');
    }
}
