<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\TeamBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * A DEPARTMENT IS A PLACEMENT, NOT AN OWNER.
 *
 * Three facts move at once, because they are one fact: a position stops
 * carrying a department, its name becomes unique across the organization, and
 * where somebody may work becomes a row of their own rather than something
 * derived through their job title.
 *
 * EXPAND, BACKFILL, CONTRACT, IN THIS ORDER. Every column that ends up NOT
 * NULL on a table that already had rows is added nullable, written, and only
 * then tightened, so a failure anywhere leaves the schema as it was and
 * nobody has to edit a vendor file to recover.
 *
 * WHAT THE BACKFILL PRESERVES is the reach each person had the moment before
 * the upgrade, which the old code DERIVED as `position -> department -> area`:
 *
 *   - a position under an AREA-level department reached that one area, and
 *     its holders belonged to that department;
 *   - a position under an ORGANIZATION-level department reached every area,
 *     and its holders belonged to that department;
 *   - a position under NO department, and a person holding no position,
 *     reached every area and belonged to no department - so they are placed
 *     across the organization and across all departments, which is what the
 *     voter already answered for them.
 *
 * Nobody gains or loses a permission in this migration. What changes is where
 * the answer is stored.
 *
 * DUPLICATE NAMES ARE RENAMED, NOT REFUSED. `Analyst` in Ecology and
 * `Analyst` in Protection were two legal rows and are now one name twice, so
 * the second and any further one take a numeric suffix and the migration
 * RAISES A NOTICE naming each: an administrator reads the rename in the
 * upgrade output and renames them into the organization's own words. Refusing
 * the migration instead would leave an installation unable to upgrade over a
 * row it was told to write.
 *
 * @destructive 1.0 - team_position.department_id and the department-scoped
 *              name index are dropped here, in the same release that stops
 *              reading them: a position carries no department in any code
 *              path after this version, the column would be unmapped, and an
 *              unmapped column makes `migrations:diff` report a change on
 *              every installation forever.
 */
final class Version20260921001000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'A position loses its department and gains seats; a person gains a placement';
    }

    public function up(Schema $schema): void
    {
        // --- EXPAND: the position's two new facts ------------------------

        $this->addSql('ALTER TABLE team_position ADD seat_count INT DEFAULT NULL');
        $this->addSql('ALTER TABLE team_position ADD allowed_kinds JSON DEFAULT NULL');

        // The kinds a position allows are the kind its holders were already
        // placed at: local where its department was an area's, organization
        // otherwise. Widening every position to both would hand an
        // installation a lever it never pulled.
        $this->addSql(<<<'SQL'
            UPDATE team_position p SET allowed_kinds = '["area"]'
            FROM team_department d
            WHERE p.department_id = d.id AND d.area_id IS NOT NULL
            SQL);
        $this->addSql(<<<'SQL'
            UPDATE team_position SET allowed_kinds = '["organization"]' WHERE allowed_kinds IS NULL
            SQL);
        $this->addSql('ALTER TABLE team_position ALTER allowed_kinds SET NOT NULL');

        // --- EXPAND: the placement ---------------------------------------

        $this->addSql(<<<'SQL'
            CREATE TABLE team_placement (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                whole_organization BOOLEAN DEFAULT FALSE NOT NULL,
                all_departments BOOLEAN DEFAULT FALSE NOT NULL,
                seeded_user_id INT DEFAULT NULL,
                PRIMARY KEY(id)
            )
            SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE team_placement_area (
                placement_id INT NOT NULL,
                area_id INT NOT NULL,
                PRIMARY KEY(placement_id, area_id)
            )
            SQL);
        $this->addSql('CREATE INDEX IDX_57617D972F966E9D ON team_placement_area (placement_id)');
        $this->addSql('CREATE INDEX IDX_57617D97BD0F409C ON team_placement_area (area_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE team_placement_department (
                placement_id INT NOT NULL,
                department_id INT NOT NULL,
                PRIMARY KEY(placement_id, department_id)
            )
            SQL);
        $this->addSql('CREATE INDEX IDX_21A7EF1A2F966E9D ON team_placement_department (placement_id)');
        $this->addSql('CREATE INDEX IDX_21A7EF1AAE80F5DF ON team_placement_department (department_id)');

        $this->addSql('ALTER TABLE team_placement_area ADD CONSTRAINT fk_team_placement_area_placement FOREIGN KEY (placement_id) REFERENCES team_placement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE team_placement_area ADD CONSTRAINT fk_team_placement_area_area FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE team_placement_department ADD CONSTRAINT fk_team_placement_dept_placement FOREIGN KEY (placement_id) REFERENCES team_placement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE team_placement_department ADD CONSTRAINT fk_team_placement_dept_department FOREIGN KEY (department_id) REFERENCES team_department (id) ON DELETE CASCADE');

        $this->addSql('ALTER TABLE team_user ADD placement_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE team_user ADD CONSTRAINT fk_team_user_placement FOREIGN KEY (placement_id) REFERENCES team_placement (id) ON DELETE SET NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C7222322F966E9D ON team_user (placement_id)');

        // --- BACKFILL: one placement per person, reproducing today's reach

        // `seeded_user_id` is how a set-based insert keeps hold of which row
        // belongs to whom; it is dropped again at the end of this same
        // version, so no installation ever runs with it.
        $this->addSql(<<<'SQL'
            INSERT INTO team_placement (whole_organization, all_departments, seeded_user_id)
            SELECT (d.area_id IS NULL), (d.id IS NULL), u.id
            FROM team_user u
            LEFT JOIN team_position p ON u.position_id = p.id
            LEFT JOIN team_department d ON p.department_id = d.id
            SQL);
        $this->addSql(<<<'SQL'
            UPDATE team_user u SET placement_id = pl.id
            FROM team_placement pl WHERE pl.seeded_user_id = u.id
            SQL);
        $this->addSql(<<<'SQL'
            INSERT INTO team_placement_area (placement_id, area_id)
            SELECT pl.id, d.area_id
            FROM team_placement pl
            JOIN team_user u ON u.id = pl.seeded_user_id
            JOIN team_position p ON u.position_id = p.id
            JOIN team_department d ON p.department_id = d.id
            WHERE d.area_id IS NOT NULL
            SQL);
        $this->addSql(<<<'SQL'
            INSERT INTO team_placement_department (placement_id, department_id)
            SELECT pl.id, d.id
            FROM team_placement pl
            JOIN team_user u ON u.id = pl.seeded_user_id
            JOIN team_position p ON u.position_id = p.id
            JOIN team_department d ON p.department_id = d.id
            SQL);

        // --- BACKFILL: one name each, and a line naming every rename ------

        $this->addSql(<<<'SQL'
            DO $$
            DECLARE row RECORD;
            BEGIN
                FOR row IN
                    SELECT p.id, p.name,
                           row_number() OVER (PARTITION BY p.name ORDER BY p.id) AS rank
                    FROM team_position p
                LOOP
                    IF row.rank > 1 THEN
                        UPDATE team_position
                        SET name = left(row.name, 114) || ' (' || row.rank || ')'
                        WHERE id = row.id;
                        RAISE NOTICE 'Position renamed: "%" is now "% (%)" - a position name is unique across the organization now, so rename it into your own words.',
                            row.name, left(row.name, 114), row.rank;
                    END IF;
                END LOOP;
            END $$
            SQL);

        // --- CONTRACT -----------------------------------------------------

        $this->addSql('DROP INDEX uniq_team_position_department_name');
        $this->addSql('CREATE UNIQUE INDEX uniq_team_position_name ON team_position (name)');
        // Dropping the column takes its foreign key with it, which is what
        // Postgres does and what down() puts back by its original name.
        $this->addSql('ALTER TABLE team_position DROP department_id');
        $this->addSql('ALTER TABLE team_placement DROP seeded_user_id');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE team_user DROP CONSTRAINT IF EXISTS fk_team_user_placement');
        $this->addSql('DROP INDEX IF EXISTS UNIQ_5C7222322F966E9D');
        $this->addSql('ALTER TABLE team_user DROP placement_id');
        $this->addSql('DROP TABLE team_placement_area');
        $this->addSql('DROP TABLE team_placement_department');
        $this->addSql('DROP TABLE team_placement');
        $this->addSql('DROP INDEX uniq_team_position_name');
        $this->addSql('ALTER TABLE team_position DROP allowed_kinds');
        $this->addSql('ALTER TABLE team_position DROP seat_count');
        $this->addSql('ALTER TABLE team_position ADD department_id INT DEFAULT NULL');
        // The name the version that created it used, so the earlier version's
        // own down() finds the constraint it expects.
        $this->addSql('ALTER TABLE team_position ADD CONSTRAINT FK_FE6E388BAE80F5DF FOREIGN KEY (department_id) REFERENCES team_department (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX uniq_team_position_department_name ON team_position (department_id, name)');
    }
}
