<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\TeamBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * WHAT THE FIGURES WERE, PERIOD BY PERIOD.
 *
 * A CLOSED PERIOD CANNOT BE RECOMPUTED, so the host writes it down while it
 * is still true: every movement, sparkline and rank change on the
 * performance page is a comparison against this table.
 *
 * EXPAND ONLY, AND NOTHING IS BACKFILLED — a period nobody recorded cannot
 * be recovered, and an invented one would be read as a measurement. An
 * installation that has never run `team:performance:snapshot` has no
 * history, which the surfaces state in words.
 *
 * ONE ROW PER DEPARTMENT, PERIOD AND FIGURE, enforced: a snapshot run by
 * hand after a scheduled one must correct the history rather than double
 * it.
 */
final class Version20260920000200 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'team_department_period_figure';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE team_department_period_figure (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              department_id INT NOT NULL,
              period_key VARCHAR(16) NOT NULL,
              figure_key VARCHAR(80) NOT NULL,
              value DOUBLE PRECISION DEFAULT NULL,
              written_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY(id)
            )
            SQL);
        $this->addSql('CREATE INDEX IDX_40E7800DAE80F5DF ON team_department_period_figure (department_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_department_period_figure ON team_department_period_figure (department_id, period_key, figure_key)');
        $this->addSql(<<<'SQL'
            ALTER TABLE team_department_period_figure
              ADD CONSTRAINT FK_40E7800DAE80F5DF FOREIGN KEY (department_id)
              REFERENCES team_department (id) ON DELETE CASCADE
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE team_department_period_figure');
    }
}
