<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\TeamBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * THE DEPARTMENT KIND — a way of grouping departments for reading.
 *
 * EXPAND ONLY, AND NOTHING IS BACKFILLED. A kind is a word the organization
 * chooses; inventing three on an installation's behalf would put words in the
 * register that nobody in the building says. Every existing department stays
 * unkinded, which is a legal state the register draws, and the first kind is
 * added on the section's Lists page.
 *
 * ON DELETE SET NULL, because deleting a word must never delete the thing it
 * described: removing a kind leaves its departments standing and unkinded.
 */
final class Version20260921000300 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'team_department_kind, and team_department.kind_id';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE team_department_kind (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                uuid UUID NOT NULL,
                name VARCHAR(80) NOT NULL,
                meaning VARCHAR(160) DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY(id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BA80C1F2D17F50A6 ON team_department_kind (uuid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_team_department_kind_name ON team_department_kind (name)');

        $this->addSql('ALTER TABLE team_department ADD kind_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE team_department ADD CONSTRAINT FK_F3C4934F30602CA9 FOREIGN KEY (kind_id) REFERENCES team_department_kind (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_F3C4934F30602CA9 ON team_department (kind_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE team_department DROP CONSTRAINT FK_F3C4934F30602CA9');
        $this->addSql('DROP INDEX IDX_F3C4934F30602CA9');
        $this->addSql('ALTER TABLE team_department DROP kind_id');
        $this->addSql('DROP TABLE team_department_kind');
    }
}
