<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\TeamBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * THE POSITION TITLE — what a position may be called.
 *
 * EXPAND ONLY, AND NOTHING IS BACKFILLED. A title is a word the organization
 * offers; minting one per existing position would fill the list with whatever
 * somebody typed into a register, including the two spellings the vocabulary
 * exists to stop. The list starts empty, which is a legal state the screen
 * draws, and the first title is added there.
 *
 * NOTHING POINTS AT IT YET, on purpose: a position still carries its own name,
 * and wiring the list into the create form is a change to the Positions
 * screen rather than to this vocabulary.
 */
final class Version20260921000400 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'team_position_title';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE team_position_title (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                uuid UUID NOT NULL,
                name VARCHAR(80) NOT NULL,
                leads_station BOOLEAN NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY(id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_208B5D41D17F50A6 ON team_position_title (uuid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_team_position_title_name ON team_position_title (name)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE team_position_title');
    }
}
