<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\ShellBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * WHAT A PERSON DID TO THEIR OWN DASHBOARD: which widgets they keep on each
 * surface, and the arrangements they saved a name for.
 *
 * Dated last of the core's five. Both tables reference `team_user` — the
 * association is mapped to `UserInterface` and resolved to the team bundle's
 * entity — and a referencing table's migration is dated after the migration
 * that creates what it references.
 *
 * `area_uuid` holds an area's uuid as a VALUE and is deliberately not a foreign
 * key: a preference is a UI scrap, and deleting an area must never be blocked
 * by one.
 */
final class Version20260101000400 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'widget_preference and widget_custom_preset';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE widget_preference (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              surface VARCHAR(64) NOT NULL,
              area_uuid UUID DEFAULT NULL,
              prefs JSON NOT NULL,
              active_kind VARCHAR(8) DEFAULT NULL,
              active_preset VARCHAR(64) DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              user_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        // Two partial indexes, not one: Postgres treats NULLs as distinct, so a
        // single unique over a nullable area_uuid would not constrain the
        // organisation-wide row at all.
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_widget_pref_surface_user_area ON widget_preference (surface, user_id, area_uuid)
            WHERE
              (area_uuid IS NOT NULL)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_widget_pref_surface_user_org ON widget_preference (surface, user_id)
            WHERE
              (area_uuid IS NULL)
        SQL);
        $this->addSql('CREATE INDEX IDX_2994E7B4A76ED395 ON widget_preference (user_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE widget_custom_preset (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              surface VARCHAR(64) NOT NULL,
              area_uuid UUID DEFAULT NULL,
              name VARCHAR(60) NOT NULL,
              layout JSON NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              uuid UUID NOT NULL,
              user_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_82A9B355D17F50A6 ON widget_custom_preset (uuid)');
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_widget_preset_surface_user_area_name ON widget_custom_preset (surface, user_id, area_uuid, name)
            WHERE
              (area_uuid IS NOT NULL)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_widget_preset_surface_user_org_name ON widget_custom_preset (surface, user_id, name)
            WHERE
              (area_uuid IS NULL)
        SQL);
        $this->addSql('CREATE INDEX IDX_82A9B355A76ED395 ON widget_custom_preset (user_id)');

        $this->addSql('ALTER TABLE widget_preference ADD CONSTRAINT FK_2994E7B4A76ED395 FOREIGN KEY (user_id) REFERENCES team_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE widget_custom_preset ADD CONSTRAINT FK_82A9B355A76ED395 FOREIGN KEY (user_id) REFERENCES team_user (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE widget_custom_preset DROP CONSTRAINT FK_82A9B355A76ED395');
        $this->addSql('ALTER TABLE widget_preference DROP CONSTRAINT FK_2994E7B4A76ED395');
        $this->addSql('DROP TABLE widget_custom_preset');
        $this->addSql('DROP TABLE widget_preference');
    }
}
