<?php

declare(strict_types=1);

/*
 * This file is part of the Uhifadhi core.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Bundle\RegistryBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * THE CATALOGUE AND THE LEDGER: every module an installation has, and which of
 * them each area has switched on.
 *
 * `area_module.aoi_id` is one of the core's cross-bundle foreign keys — the
 * association is mapped to `AreaInterface` and resolved to the area bundle's
 * entity — so it is declared HERE, in the migration of the bundle that owns the
 * referencing table, and it is dated after the migration that creates
 * `area_of_interest`.
 */
final class Version20260101000200 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'module and area_module';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE module (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              slug VARCHAR(40) NOT NULL,
              name VARCHAR(80) NOT NULL,
              category VARCHAR(255) NOT NULL,
              status VARCHAR(255) NOT NULL,
              data_source VARCHAR(80) NOT NULL,
              pinned BOOLEAN NOT NULL,
              position INT NOT NULL,
              icon VARCHAR(40) DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              uuid UUID NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C242628989D9B62 ON module (slug)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C242628D17F50A6 ON module (uuid)');

        $this->addSql(<<<'SQL'
            CREATE TABLE area_module (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              active BOOLEAN NOT NULL,
              position INT NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              uuid UUID NOT NULL,
              module_id INT NOT NULL,
              aoi_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6AAFD7AAD17F50A6 ON area_module (uuid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_area_module ON area_module (aoi_id, module_id)');
        $this->addSql('CREATE INDEX IDX_6AAFD7AAAFC2B591 ON area_module (module_id)');
        $this->addSql('CREATE INDEX IDX_6AAFD7AAB626396B ON area_module (aoi_id)');

        $this->addSql('ALTER TABLE area_module ADD CONSTRAINT FK_6AAFD7AAAFC2B591 FOREIGN KEY (module_id) REFERENCES module (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE area_module ADD CONSTRAINT FK_6AAFD7AAB626396B FOREIGN KEY (aoi_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE area_module DROP CONSTRAINT FK_6AAFD7AAAFC2B591');
        $this->addSql('ALTER TABLE area_module DROP CONSTRAINT FK_6AAFD7AAB626396B');
        $this->addSql('DROP TABLE area_module');
        $this->addSql('DROP TABLE module');
    }
}
